.travis.yml:

before_script:
  - npm install
  - mysql --local-infile -u root < ./database_setup/database-setup.sql
  - nodejs ./database_setup/database-setup.js
  - mysql --local-infile -u root < ./database_setup/database-setup-2.sql
  - nodejs ./database_setup/manualAdminSetup.js

script: mocha ./test/dataTest.js
