.travis.yml:

language: node_js

node_js:
  - "4.4.4"

before_script:
  - npm install

script:
    - mysql --local-infile -u root < ./database_setup/database-setup.sql
    - node ./database_setup/database-setup.js
    - mysql --local-infile -u root < ./database_setup/database-setup-2.sql
    - node ./database_setup/manualAdminSetup.js
    - mocha ./test/dataTest.js
