.travis.yml:

language: node_js

node_js:
  - "4.4.4"

env:
  - MYSQL_URL='mysql://root:@127.0.0.1/nelisa_another_copy'

script:
    - npm install
    - mysql --local-infile -u root < ./database_setup/database-setup.sql
    - node ./database_setup/database-setup.js
    - mysql --local-infile -u root < ./database_setup/database-setup-2.sql
    - node ./database_setup/manualAdminSetup.js
    - mocha ./test/dataTest.js
