#!/bin/bash
mysql --local-infile -u root -p1amdan13l < ./database_setup/database-setup.sql
node ./database_setup/database-setup.js
mysql --local-infile -u root -p1amdan13l < ./database_setup/database-setup-2.sql
node ./database_setup/manualAdminSetup.js
